# models:
#  name of the model:
#    intent_model: file localization
#    nlu_model: adress:port
#    language: language of the model (for tokenization)
port: 9009
threads: 2
debug: 0

models:
  ner:
    intent_model: resources/intent_model
    nlu_model: localhost:9008
    language: fr
