version: "3"
services:
  nlu:
    image: text-nlu:latest
    ports:
      - "9009:9009"
    volumes:
      - ./models:/models
    environment:
      API_TC_TFSERVING_HOST: tensorflow_serving:8500
      API_TC_THREADS: 1
      API_TC_PORT: 9009
      API_TC_CONFIG: /models/models_config.yaml
      API_TC_GRPC: 0
      API_TC_DEBUG: 1

  tensorflow_serving:
    image: "tensorflow/serving:latest"
    volumes:
      - ./models:/models
    command: --model_config_file=/models/models_config.yaml
    # We can't set MODEL_CONFIG_FILE environment variable:
    # See https://github.com/tensorflow/serving/issues/1165